### ISSUE TITLE
Feedback from Prof. Hong and UI Overall

### ISSUE THREAD

**Issue by bobleesj** [CooperExchange/UI#14]
Feedback from Prof. Hong:
- [x] Remove the white rectangle in the main screen at the beginning
- [x] Have a dropdown for buy/sell; it’s weird to type them 
- [x] The screen stays on the buy/sell page after buying/selling. 
- [x] Show the old account settings as it’s weird to let someone change it without seeing the old info 

Other feedback
- [x] If there is no trade, add a placeholder Ex) “No assets available”
- [x] Add commas “,” Ex) $1,000,000 for total net worth & remaining cash
- [x] When the user deposit/withdraw, it should pop up either error/success message.
- [x] same feedback for the “Execute Update Settings” button.
- [x] same feedback for the “Execute Trade” button
- [x] On the “History” channel, the text should be “no history available” instead of "Loading…”  for a new user.
- [x] same feedback for the Trade History page
- [x] Add a few example tickers for the stocks/cryptos as discussed or make a dropdown of a list of actual company/crypto names like Ex) “Tesla”

**Comment by alizameller** [comment]
Thanks for adding this bob. Working through these changes now

**Comment by EvanKluger** [comment]
Just added a PR addressing the search bar issue. Once that is merged everything on the list is complete.
